#####################
### Dockerfile webui ###
#####################
FROM python:3.12 AS fabric-base

# Install sudo and expect
RUN apt-get update -y \
    && apt-get install -y sudo expect ffmpeg \
    && pip install --upgrade pip pipx \
    && apt-get clean

# Setup fabric user, workdir, and copy files
COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd
RUN useradd --create-home -G sudo --shell /bin/bash fabric-user
WORKDIR /home/fabric-user/
USER fabric-user

# Copy project files and install dependencies
COPY . /home/fabric-user/fabric
RUN pipx install /home/fabric-user/fabric
ENV PATH="${PATH}:/home/fabric-user/.local/bin"

# Create an expect script to automate fabric --setup
RUN echo '#!/usr/bin/expect\n\
spawn fabric --setup\n\
expect "Please enter your OpenAI API key. If you do not have one or if you have already entered it, press enter."\n\
send "\r"\n\
expect "Please enter your claude API key. If you do not have one, or if you have already entered it, press enter."\n\
send "\r"\n\
expect "Please enter your Google API key. If you do not have one, or if you have already entered it, press enter."\n\
send "\r"\n\
expect "Please enter your YouTube API key. If you do not have one, or if you have already entered it, press enter."\n\
send "\r"\n\
interact' > /home/fabric-user/fabric_setup.exp \
    && chmod +x /home/fabric-user/fabric_setup.exp

# Run the expect script to setup fabric
RUN /home/fabric-user/fabric_setup.exp

FROM fabric-base AS fabric-setup

WORKDIR /home/fabric-user/fabric
USER fabric-user

COPY .env /home/.config/fabric/.env

# COPY .env /home/.config/fabric/.env

# Setup envs to use in the .env file that pipx creates
# ENV DEFAULT_MODEL=default_model
# ENV FABRIC_FRONTMATTER=""
# ENV FABRIC_OUTPUT_PATH=$(pwd)
# ENV OPENAI_BASE_URL=https://YOUR-SERVER:8000/v1/
# ENV OPENAI_API_KEY=api_key
# ENV CLAUDE_API_KEY=api_key
# ENV GOOGLE_API_KEY=api_key
# ENV YOUTUBE_API_KEY=api_key

# Expose necessary ports and set command
EXPOSE 13337
# EXPOSE 13338
CMD ["fabric-webui"]
# CMD ["fabric-api"]
