##############################
### Dockerfile fabric-base ###
##############################
FROM python:3.10 AS fabric-base

# Install sudo and expect
RUN apt-get update -y \
    && apt-get install -y sudo expect ffmpeg \
    && pip install --upgrade pip pipx \
    && apt-get clean

# Setup fabric user, workdir, and copy files
COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd
RUN useradd --create-home -G sudo --shell /bin/bash fabric-user
WORKDIR /home/fabric-user/
USER fabric-user

# Copy project files and install dependencies
COPY . /home/fabric-user/fabric
RUN pipx install /home/fabric-user/fabric
ENV PATH="${PATH}:/home/fabric-user/.local/bin"

# Install script to automatically run `fabric --setup`
RUN /home/fabric-user/fabric/setup.sh


#############################
### Dockerfile fabric-api ###
#############################
FROM fabric-base AS fabric-api

WORKDIR /home/fabric-user/fabric
USER fabric-user

# COPY .env /home/.config/fabric/.env
RUN echo "" > /home/fabric-user/.config/fabric/.env

# Setup envs to use in the .env file that pipx creates
ENV DEFAULT_MODEL=gpt-4o
ENV FABRIC_FRONTMATTER=""
ENV FABRIC_OUTPUT_PATH=/home/fabric-user/fabric/save
ENV OPENAI_BASE_URL=http://host.docker.internal:11434/v1
ENV OPENAI_API_KEY=api_key
ENV CLAUDE_API_KEY=api_key
ENV GOOGLE_API_KEY=api_key
ENV YOUTUBE_API_KEY=api_key
ENV REMOTE_OLLAMA_URL=http://host.docker.internal:11434/v1

# Expose necessary ports and set command
RUN /home/fabric-user/fabric/installer/server/api/00-entrypoint-script.sh
EXPOSE 13337
CMD ["fabric-api"]
